# MIT License
#
# Copyright (c) 2022 Francesco Galisi
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

FROM openjdk:8-jdk
WORKDIR /netlogo
RUN wget https://ccl.northwestern.edu/netlogo/6.2.2/NetLogo-6.2.2-64.tgz \
    && tar zxvpf NetLogo-6.2.2-64.tgz \
    && rm NetLogo-6.2.2-64.tgz \
    && mv NetLogo\ 6.2.2/* . \
    && rm -rf mv NetLogo\ 6.2.2
WORKDIR /app
RUN apt-get update -y
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
COPY sciadro-3.1/ ./sciadro/
COPY differential_evolution/requirements.txt differential_evolution/requirements.txt
RUN pip3 install -r differential_evolution/requirements.txt
COPY differential_evolution/java differential_evolution/java
WORKDIR /app/differential_evolution/java
RUN make clean
RUN make SimulationServer NETLOGO_HOME=/netlogo
WORKDIR /app
COPY differential_evolution/differential_evolution.py differential_evolution/differential_evolution.py
COPY differential_evolution/parameters.json differential_evolution/parameters.json
ENTRYPOINT ["python3", "differential_evolution/differential_evolution.py", "/netlogo", "sciadro/SCD src.nlogo"]
CMD ["fire1", "differential_evolution/parameters.json"]